kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-web
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      access: accepted
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web2