apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: c1
    image: busybox:1.31.1
    command: ["sh", "-c", "while true; do echo $(hostname) $(date) >> /vol/date.log; sleep 10; done"]
    volumeMounts:
    - name: vol
      mountPath: /vol
  - name: c2
    image: busybox:1.31.1
    command: ["sh", "-c", "while true; do "tail /vol/date.log"; done]
    volumeMounts:
    - name: vol
      mountPath: /vol
  volumes:
  - name: vol
    emptyDir: {}